#!/bin/sh -x
# vim: ft=sh
set -e
mkdir -p ~/src
cd ~/src

case "$CZMQ_VERSION" in
HEAD)
	echo "Using latest commit (HEAD) and compiling with --enable-drafts ..."
	git pull origin master
	CONFIGURE_OPTS="--enable-drafts=yes"
	;;
stable)
	echo "Using latest stable release ..."
	tag=`git tag | grep ^v | grep -v -- -rc | sort --field-separator=. --key=1,3 --numeric-sort | tail -1`
	echo "Using tag: $tag"
	git pull origin master
	git checkout $tag
	CONFIGURE_OPTS="--enable-drafts=no"
	;;
*)
	echo '$CZMQ_VERSION not set.'
	exit 1
esac

./autogen.sh
./configure $CONFIGURE_OPTS
make
sudo make install
