#!/bin/sh -x
# vim: ft=sh
set -e
mkdir -p ~/src
cd ~/src

case "$ZMQ_VERSION" in
HEAD)
	echo "Using HEAD and compiling with --enable-drafts ..."
	git clone --depth 1 https://github.com/zeromq/libzmq libzmq
	;;
v*)
	echo "Using $ZMQ_VERSION and compiling with --enable-drafts ..."
	git clone --depth 1 --branch "$ZMQ_VERSION" https://github.com/zeromq/libzmq libzmq
	;;
*)
	echo '$ZMQ_VERSION not set.'
	exit 1
esac

cd libzmq
./autogen.sh
./configure --prefix=$HOME --enable-drafts=yes
make
make install
