#!/bin/sh -x
# vim: ft=sh
set -e
mkdir -p ~/src
cd ~/src

case "$ZMQ_VERSION" in
HEAD)
	echo "Using HEAD and compiling with --enable-drafts ..."
	git clone https://github.com/zeromq/libzmq libzmq
	CONFIGURE_OPTS="--enable-drafts=yes"
	;;
*)
	echo '$ZMQ_VERSION not set.'
	exit 1
esac

cd libzmq
./autogen.sh
./configure $CONFIGURE_OPTS
make
sudo make install
