#!/bin/sh -x
# vim: ft=sh
set -e
mkdir -p ~/src
cd ~/src

case "$CZMQ_VERSION" in
HEAD)
	echo "Using HEAD and compiling with --enable-drafts ..."
	git clone https://github.com/zeromq/czmq czmq
	CONFIGURE_OPTS="--enable-drafts=yes"
	;;
*)
	echo '$CZMQ_VERSION not set.'
	exit 1
esac

cd czmq
./autogen.sh
./configure $CONFIGURE_OPTS
make
sudo make install
