#!/bin/sh -x
# vim: ft=sh
set -e
mkdir -p ~/src
cd ~/src

case "$CZMQ_VERSION" in
HEAD)
	echo "Using HEAD and compiling with --enable-drafts ..."
	git clone --depth 1 https://github.com/zeromq/czmq czmq
	;;
v*)
	echo "Using $CZMQ_VERSION and compiling with --enable-drafts ..."
	git clone --depth 1 --branch "$CZMQ_VERSION" https://github.com/zeromq/czmq czmq
	;;
*)
	echo '$CZMQ_VERSION not set.'
	exit 1
esac

cd czmq
./autogen.sh
./configure --prefix=$HOME --enable-drafts=yes
make
make install
