name: Coverage

on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1
    - name: Install CZMQ
      run: sudo apt-get install libczmq-dev
    - name: Run the default task
      run: |
        gem install bundler
        bundle install
        env REPORT_COVERAGE=true bundle exec rake
