name: STABLE API

on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        ruby:
          - '3.0'
          - '3.1'
          - '3.2'
          - '3.3'
          - '3.4'
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby ${{ matrix.ruby }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Install CZMQ
      run: sudo apt-get install libczmq-dev
    - name: Run the default task
      run: |
        gem install bundler
        bundle install
        bundle exec rake
